spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/visitors?useUnicode=true&charset=utf8mb4&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    paswword:
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: false
